/// Direction of a search operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SearchDirection {
    Forward,
    Backward,
}

impl SearchDirection {
    pub fn opposite(self) -> Self {
        match self {
            SearchDirection::Forward => SearchDirection::Backward,
            SearchDirection::Backward => SearchDirection::Forward,
        }
    }
}

/// All actions the editor can perform.
///
/// Unit variants are configurable — they can appear in config.kdl.
/// Data-carrying variants are runtime-only (generated by the input layer).
#[derive(Debug, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Action {
    // -- Movement --
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    MoveWordForward,
    MoveWordEnd,
    MoveWordBackward,
    MoveBigWordForward,
    MoveBigWordEnd,
    MoveBigWordBackward,
    MoveToLineStart,
    MoveToLineEnd,
    MoveToFirstLine,
    MoveToLastLine,
    PageUp,
    PageDown,
    HalfPageUp,
    HalfPageDown,
    ScrollUp,
    ScrollDown,

    // -- Editing --
    InsertNewline,
    DeleteCharBackward,
    DeleteCharForward,
    DeleteWordBackward,
    DeleteLine,
    DeleteToLineEnd,
    ChangeToLineEnd,
    InsertLineBelow,
    InsertLineAbove,
    Undo,
    Redo,

    // -- Clipboard --
    YankLine,
    Paste,
    PasteBefore,

    // -- Operators (await a motion) --
    OperatorDelete,
    OperatorChange,
    OperatorYank,

    // -- Visual mode operations --
    VisualDelete,
    VisualChange,
    VisualYank,
    VisualSurround,

    // -- Jump history --
    JumpBack,
    JumpForward,

    // -- Search --
    EnterSearchForward,
    EnterSearchBackward,
    SearchNext,
    SearchPrev,

    // -- Mode changes --
    EnterInsertMode,
    EnterInsertModeAppend,
    EnterInsertModeLineEnd,
    EnterInsertModeLineStart,
    EnterNormalMode,
    EnterVisualMode,
    EnterCommandMode,

    // -- Buffer management --
    NextBuffer,
    PrevBuffer,
    CloseBuffer,
    SaveBuffer,
    OpenRecentPicker,

    // -- Window management --
    SplitVertical,
    SplitHorizontal,
    FocusPaneNext,
    FocusPanePrev,
    FocusPaneLeft,
    FocusPaneRight,
    FocusPaneUp,
    FocusPaneDown,
    MovePaneLeft,
    MovePaneRight,
    MovePaneUp,
    MovePaneDown,
    ClosePane,

    // -- File browser --
    OpenFileBrowser,
    OpenFileBrowserHome,
    BrowserOpen,
    BrowserParentDir,
    BrowserFilter,
    BrowserNewFile,
    BrowserClose,
    BrowserHome,

    // -- Editor --
    Quit,
    ForceQuit,
    QuitAll,
    ForceQuitAll,

    // -- Command palette --
    CommandPalette,

    // -- Macros --
    RecordMacro,
    PlayMacro,

    // -- Comment --
    CommentToggle,

    // -- Terminal --
    OpenTerminal,

    // -- Runtime-only --
    InsertChar(char),
    ExecuteCommand(String),
    SaveBufferAs(String),
    GotoLine(usize),
    SearchExecute(String, SearchDirection),
    SearchCancel,
    Noop,
}

/// Single source of truth for all configurable actions.
/// Each entry: (config_name, display_name, Action).
/// Runtime-only variants (InsertChar, GotoLine, etc.) are NOT in this table.
const ACTION_TABLE: &[(&str, &str, Action)] = &[
    // Movement
    ("MoveUp", "Move up", Action::MoveUp),
    ("MoveDown", "Move down", Action::MoveDown),
    ("MoveLeft", "Move left", Action::MoveLeft),
    ("MoveRight", "Move right", Action::MoveRight),
    ("MoveWordForward", "Move word forward", Action::MoveWordForward),
    ("MoveWordEnd", "Move to end of word", Action::MoveWordEnd),
    ("MoveWordBackward", "Move word backward", Action::MoveWordBackward),
    ("MoveBigWordForward", "Move WORD forward", Action::MoveBigWordForward),
    ("MoveBigWordEnd", "Move to end of WORD", Action::MoveBigWordEnd),
    ("MoveBigWordBackward", "Move WORD backward", Action::MoveBigWordBackward),
    ("MoveToLineStart", "Move to line start", Action::MoveToLineStart),
    ("MoveToLineEnd", "Move to line end", Action::MoveToLineEnd),
    ("MoveToFirstLine", "Move to first line", Action::MoveToFirstLine),
    ("MoveToLastLine", "Move to last line", Action::MoveToLastLine),
    ("PageUp", "Page up", Action::PageUp),
    ("PageDown", "Page down", Action::PageDown),
    ("HalfPageUp", "Half page up", Action::HalfPageUp),
    ("HalfPageDown", "Half page down", Action::HalfPageDown),
    ("ScrollUp", "Scroll up", Action::ScrollUp),
    ("ScrollDown", "Scroll down", Action::ScrollDown),
    // Editing
    ("InsertNewline", "Insert newline", Action::InsertNewline),
    ("DeleteCharBackward", "Delete char backward", Action::DeleteCharBackward),
    ("DeleteCharForward", "Delete char forward", Action::DeleteCharForward),
    ("DeleteWordBackward", "Delete word backward", Action::DeleteWordBackward),
    ("DeleteLine", "Delete line", Action::DeleteLine),
    ("DeleteToLineEnd", "Delete to line end", Action::DeleteToLineEnd),
    ("ChangeToLineEnd", "Change to line end", Action::ChangeToLineEnd),
    ("InsertLineBelow", "Insert line below", Action::InsertLineBelow),
    ("InsertLineAbove", "Insert line above", Action::InsertLineAbove),
    ("Undo", "Undo", Action::Undo),
    ("Redo", "Redo", Action::Redo),
    // Clipboard
    ("YankLine", "Yank line", Action::YankLine),
    ("Paste", "Paste after", Action::Paste),
    ("PasteBefore", "Paste before", Action::PasteBefore),
    // Operators
    ("OperatorDelete", "Delete (operator)", Action::OperatorDelete),
    ("OperatorChange", "Change (operator)", Action::OperatorChange),
    ("OperatorYank", "Yank (operator)", Action::OperatorYank),
    // Visual
    ("VisualDelete", "Delete selection", Action::VisualDelete),
    ("VisualChange", "Change selection", Action::VisualChange),
    ("VisualYank", "Yank selection", Action::VisualYank),
    ("VisualSurround", "Surround selection", Action::VisualSurround),
    // Jump history
    ("JumpBack", "Jump back", Action::JumpBack),
    ("JumpForward", "Jump forward", Action::JumpForward),
    // Search
    ("EnterSearchForward", "Search forward", Action::EnterSearchForward),
    ("EnterSearchBackward", "Search backward", Action::EnterSearchBackward),
    ("SearchNext", "Search next", Action::SearchNext),
    ("SearchPrev", "Search previous", Action::SearchPrev),
    // Mode changes
    ("EnterInsertMode", "Enter insert mode", Action::EnterInsertMode),
    ("EnterInsertModeAppend", "Enter insert mode (append)", Action::EnterInsertModeAppend),
    ("EnterInsertModeLineEnd", "Enter insert mode (line end)", Action::EnterInsertModeLineEnd),
    ("EnterInsertModeLineStart", "Enter insert mode (line start)", Action::EnterInsertModeLineStart),
    ("EnterNormalMode", "Enter normal mode", Action::EnterNormalMode),
    ("EnterVisualMode", "Enter visual mode", Action::EnterVisualMode),
    ("EnterCommandMode", "Enter command mode", Action::EnterCommandMode),
    // Buffer management
    ("NextBuffer", "Next buffer", Action::NextBuffer),
    ("PrevBuffer", "Previous buffer", Action::PrevBuffer),
    ("CloseBuffer", "Close buffer", Action::CloseBuffer),
    ("SaveBuffer", "Save buffer", Action::SaveBuffer),
    ("OpenRecentPicker", "Recent files", Action::OpenRecentPicker),
    // Window management
    ("SplitVertical", "Split vertical", Action::SplitVertical),
    ("SplitHorizontal", "Split horizontal", Action::SplitHorizontal),
    ("FocusPaneNext", "Focus next pane", Action::FocusPaneNext),
    ("FocusPanePrev", "Focus previous pane", Action::FocusPanePrev),
    ("FocusPaneLeft", "Focus pane left", Action::FocusPaneLeft),
    ("FocusPaneRight", "Focus pane right", Action::FocusPaneRight),
    ("FocusPaneUp", "Focus pane up", Action::FocusPaneUp),
    ("FocusPaneDown", "Focus pane down", Action::FocusPaneDown),
    ("MovePaneLeft", "Move pane left", Action::MovePaneLeft),
    ("MovePaneRight", "Move pane right", Action::MovePaneRight),
    ("MovePaneUp", "Move pane up", Action::MovePaneUp),
    ("MovePaneDown", "Move pane down", Action::MovePaneDown),
    ("ClosePane", "Close pane", Action::ClosePane),
    // File browser
    ("OpenFileBrowser", "Open file browser", Action::OpenFileBrowser),
    ("OpenFileBrowserHome", "Open file browser (home)", Action::OpenFileBrowserHome),
    ("BrowserOpen", "Browser: open", Action::BrowserOpen),
    ("BrowserParentDir", "Browser: parent directory", Action::BrowserParentDir),
    ("BrowserFilter", "Browser: filter", Action::BrowserFilter),
    ("BrowserNewFile", "Browser: new file", Action::BrowserNewFile),
    ("BrowserClose", "Browser: close", Action::BrowserClose),
    ("BrowserHome", "Browser: go home", Action::BrowserHome),
    // Editor
    ("Quit", "Quit (close buffer)", Action::Quit),
    ("ForceQuit", "Force quit (close buffer)", Action::ForceQuit),
    ("QuitAll", "Quit all", Action::QuitAll),
    ("ForceQuitAll", "Force quit all", Action::ForceQuitAll),
    // Command palette
    ("CommandPalette", "Command palette", Action::CommandPalette),
    // Macros
    ("RecordMacro", "Record macro", Action::RecordMacro),
    ("PlayMacro", "Play macro", Action::PlayMacro),
    // Comment
    ("CommentToggle", "Toggle line comment", Action::CommentToggle),
    // Terminal
    ("OpenTerminal", "Open terminal", Action::OpenTerminal),
];

impl Action {
    /// Parse an action name from config. Returns None for unknown names.
    pub fn from_name(name: &str) -> Option<Self> {
        ACTION_TABLE.iter()
            .find(|(config_name, _, _)| *config_name == name)
            .map(|(_, _, action)| action.clone())
    }

    /// Human-readable name for display in the command palette.
    pub fn display_name(&self) -> &'static str {
        // Look up configurable actions in the table.
        for (_, display, action) in ACTION_TABLE {
            if action == self {
                return display;
            }
        }
        // Runtime-only variants not in the table.
        match self {
            Action::InsertChar(_) => "Insert char",
            Action::ExecuteCommand(_) => "Execute command",
            Action::SaveBufferAs(_) => "Save buffer as",
            Action::GotoLine(_) => "Go to line",
            Action::SearchExecute(_, _) => "Execute search",
            Action::SearchCancel => "Cancel search",
            Action::Noop => "No-op",
            _ => "Unknown",
        }
    }

    /// All configurable actions (excludes runtime-only variants).
    pub fn all_configurable() -> Vec<Action> {
        ACTION_TABLE.iter().map(|(_, _, action)| action.clone()).collect()
    }

    /// Whether this action is a motion that can compose with an operator.
    pub fn is_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveUp
                | Action::MoveDown
                | Action::MoveLeft
                | Action::MoveRight
                | Action::MoveWordForward
                | Action::MoveWordEnd
                | Action::MoveWordBackward
                | Action::MoveBigWordForward
                | Action::MoveBigWordEnd
                | Action::MoveBigWordBackward
                | Action::MoveToLineStart
                | Action::MoveToLineEnd
                | Action::MoveToFirstLine
                | Action::MoveToLastLine
                | Action::PageUp
                | Action::PageDown
                | Action::HalfPageUp
                | Action::HalfPageDown
                | Action::GotoLine(_)
        )
    }

    /// Whether this motion is exclusive (destination char NOT included in operator range).
    /// Vim rule: inclusive motions include the destination, exclusive motions don't.
    pub fn is_exclusive_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveLeft
                | Action::MoveRight
                | Action::MoveWordForward
                | Action::MoveWordBackward
                | Action::MoveBigWordForward
                | Action::MoveBigWordBackward
                | Action::MoveToLineStart
        )
    }

    /// Whether this motion moves backward (left/up direction).
    /// Used to resolve empty operator ranges: forward motions clamped at a
    /// boundary still act on one character, backward motions don't.
    pub fn is_backward_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveLeft
                | Action::MoveWordBackward
                | Action::MoveBigWordBackward
                | Action::MoveToLineStart
        )
    }

    /// Whether this motion operates on whole lines (linewise).
    pub fn is_linewise_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveUp
                | Action::MoveDown
                | Action::MoveToFirstLine
                | Action::MoveToLastLine
                | Action::PageUp
                | Action::PageDown
                | Action::HalfPageUp
                | Action::HalfPageDown
                | Action::GotoLine(_)
        )
    }
}
