/// Direction of a search operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SearchDirection {
    Forward,
    Backward,
}

impl SearchDirection {
    pub fn opposite(self) -> Self {
        match self {
            SearchDirection::Forward => SearchDirection::Backward,
            SearchDirection::Backward => SearchDirection::Forward,
        }
    }
}

/// All actions the editor can perform.
///
/// Unit variants are configurable — they can appear in config.kdl.
/// Data-carrying variants are runtime-only (generated by the input layer).
#[derive(Debug, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub enum Action {
    // -- Movement --
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    MoveWordForward,
    MoveWordEnd,
    MoveWordBackward,
    MoveBigWordForward,
    MoveBigWordEnd,
    MoveBigWordBackward,
    MoveToLineStart,
    MoveToLineEnd,
    MoveToFirstLine,
    MoveToLastLine,
    PageUp,
    PageDown,
    HalfPageUp,
    HalfPageDown,
    ScrollUp,
    ScrollDown,

    // -- Editing --
    InsertNewline,
    DeleteCharBackward,
    DeleteCharForward,
    DeleteLine,
    InsertLineBelow,
    InsertLineAbove,
    Undo,
    Redo,

    // -- Clipboard --
    YankLine,
    Paste,
    PasteBefore,

    // -- Operators (await a motion) --
    OperatorDelete,
    OperatorChange,
    OperatorYank,

    // -- Visual mode operations --
    VisualDelete,
    VisualChange,
    VisualYank,

    // -- Jump history --
    JumpBack,
    JumpForward,

    // -- Search --
    EnterSearchForward,
    EnterSearchBackward,
    SearchNext,
    SearchPrev,

    // -- Mode changes --
    EnterInsertMode,
    EnterInsertModeAppend,
    EnterInsertModeLineEnd,
    EnterInsertModeLineStart,
    EnterNormalMode,
    EnterVisualMode,
    EnterCommandMode,

    // -- Buffer management --
    NextBuffer,
    PrevBuffer,
    CloseBuffer,
    SaveBuffer,

    // -- Window management --
    SplitVertical,
    SplitHorizontal,
    FocusPaneNext,
    FocusPanePrev,
    FocusPaneLeft,
    FocusPaneRight,
    FocusPaneUp,
    FocusPaneDown,
    MovePaneLeft,
    MovePaneRight,
    MovePaneUp,
    MovePaneDown,
    ClosePane,

    // -- File browser --
    OpenFileBrowser,
    OpenFileBrowserHome,
    BrowserOpen,
    BrowserParentDir,
    BrowserFilter,
    BrowserNewFile,
    BrowserClose,
    BrowserHome,

    // -- Editor --
    Quit,
    ForceQuit,
    QuitAll,
    ForceQuitAll,

    // -- Command palette --
    CommandPalette,

    // -- Runtime-only --
    InsertChar(char),
    ExecuteCommand(String),
    SaveBufferAs(String),
    GotoLine(usize),
    SearchExecute(String, SearchDirection),
    SearchCancel,
    Noop,
}

impl Action {
    /// Parse an action name from config. Returns None for unknown names.
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "MoveUp" => Some(Action::MoveUp),
            "MoveDown" => Some(Action::MoveDown),
            "MoveLeft" => Some(Action::MoveLeft),
            "MoveRight" => Some(Action::MoveRight),
            "MoveWordForward" => Some(Action::MoveWordForward),
            "MoveWordEnd" => Some(Action::MoveWordEnd),
            "MoveWordBackward" => Some(Action::MoveWordBackward),
            "MoveBigWordForward" => Some(Action::MoveBigWordForward),
            "MoveBigWordEnd" => Some(Action::MoveBigWordEnd),
            "MoveBigWordBackward" => Some(Action::MoveBigWordBackward),
            "MoveToLineStart" => Some(Action::MoveToLineStart),
            "MoveToLineEnd" => Some(Action::MoveToLineEnd),
            "MoveToFirstLine" => Some(Action::MoveToFirstLine),
            "MoveToLastLine" => Some(Action::MoveToLastLine),
            "PageUp" => Some(Action::PageUp),
            "PageDown" => Some(Action::PageDown),
            "HalfPageUp" => Some(Action::HalfPageUp),
            "HalfPageDown" => Some(Action::HalfPageDown),
            "ScrollUp" => Some(Action::ScrollUp),
            "ScrollDown" => Some(Action::ScrollDown),
            "InsertNewline" => Some(Action::InsertNewline),
            "DeleteCharBackward" => Some(Action::DeleteCharBackward),
            "DeleteCharForward" => Some(Action::DeleteCharForward),
            "DeleteLine" => Some(Action::DeleteLine),
            "InsertLineBelow" => Some(Action::InsertLineBelow),
            "InsertLineAbove" => Some(Action::InsertLineAbove),
            "Undo" => Some(Action::Undo),
            "Redo" => Some(Action::Redo),
            "YankLine" => Some(Action::YankLine),
            "Paste" => Some(Action::Paste),
            "PasteBefore" => Some(Action::PasteBefore),
            "OperatorDelete" => Some(Action::OperatorDelete),
            "OperatorChange" => Some(Action::OperatorChange),
            "OperatorYank" => Some(Action::OperatorYank),
            "VisualDelete" => Some(Action::VisualDelete),
            "VisualChange" => Some(Action::VisualChange),
            "VisualYank" => Some(Action::VisualYank),
            "JumpBack" => Some(Action::JumpBack),
            "JumpForward" => Some(Action::JumpForward),
            "EnterSearchForward" => Some(Action::EnterSearchForward),
            "EnterSearchBackward" => Some(Action::EnterSearchBackward),
            "SearchNext" => Some(Action::SearchNext),
            "SearchPrev" => Some(Action::SearchPrev),
            "EnterInsertMode" => Some(Action::EnterInsertMode),
            "EnterInsertModeAppend" => Some(Action::EnterInsertModeAppend),
            "EnterInsertModeLineEnd" => Some(Action::EnterInsertModeLineEnd),
            "EnterInsertModeLineStart" => Some(Action::EnterInsertModeLineStart),
            "EnterNormalMode" => Some(Action::EnterNormalMode),
            "EnterVisualMode" => Some(Action::EnterVisualMode),
            "EnterCommandMode" => Some(Action::EnterCommandMode),
            "NextBuffer" => Some(Action::NextBuffer),
            "PrevBuffer" => Some(Action::PrevBuffer),
            "CloseBuffer" => Some(Action::CloseBuffer),
            "SaveBuffer" => Some(Action::SaveBuffer),
            "SplitVertical" => Some(Action::SplitVertical),
            "SplitHorizontal" => Some(Action::SplitHorizontal),
            "FocusPaneNext" => Some(Action::FocusPaneNext),
            "FocusPanePrev" => Some(Action::FocusPanePrev),
            "FocusPaneLeft" => Some(Action::FocusPaneLeft),
            "FocusPaneRight" => Some(Action::FocusPaneRight),
            "FocusPaneUp" => Some(Action::FocusPaneUp),
            "FocusPaneDown" => Some(Action::FocusPaneDown),
            "MovePaneLeft" => Some(Action::MovePaneLeft),
            "MovePaneRight" => Some(Action::MovePaneRight),
            "MovePaneUp" => Some(Action::MovePaneUp),
            "MovePaneDown" => Some(Action::MovePaneDown),
            "ClosePane" => Some(Action::ClosePane),
            "OpenFileBrowser" => Some(Action::OpenFileBrowser),
            "OpenFileBrowserHome" => Some(Action::OpenFileBrowserHome),
            "BrowserOpen" => Some(Action::BrowserOpen),
            "BrowserParentDir" => Some(Action::BrowserParentDir),
            "BrowserFilter" => Some(Action::BrowserFilter),
            "BrowserNewFile" => Some(Action::BrowserNewFile),
            "BrowserClose" => Some(Action::BrowserClose),
            "BrowserHome" => Some(Action::BrowserHome),
            "Quit" => Some(Action::Quit),
            "ForceQuit" => Some(Action::ForceQuit),
            "QuitAll" => Some(Action::QuitAll),
            "ForceQuitAll" => Some(Action::ForceQuitAll),
            "CommandPalette" => Some(Action::CommandPalette),
            _ => None,
        }
    }

    /// Human-readable name for display in the command palette.
    pub fn display_name(&self) -> &'static str {
        match self {
            Action::MoveUp => "Move up",
            Action::MoveDown => "Move down",
            Action::MoveLeft => "Move left",
            Action::MoveRight => "Move right",
            Action::MoveWordForward => "Move word forward",
            Action::MoveWordEnd => "Move to end of word",
            Action::MoveWordBackward => "Move word backward",
            Action::MoveBigWordForward => "Move WORD forward",
            Action::MoveBigWordEnd => "Move to end of WORD",
            Action::MoveBigWordBackward => "Move WORD backward",
            Action::MoveToLineStart => "Move to line start",
            Action::MoveToLineEnd => "Move to line end",
            Action::MoveToFirstLine => "Move to first line",
            Action::MoveToLastLine => "Move to last line",
            Action::PageUp => "Page up",
            Action::PageDown => "Page down",
            Action::HalfPageUp => "Half page up",
            Action::HalfPageDown => "Half page down",
            Action::ScrollUp => "Scroll up",
            Action::ScrollDown => "Scroll down",
            Action::InsertNewline => "Insert newline",
            Action::DeleteCharBackward => "Delete char backward",
            Action::DeleteCharForward => "Delete char forward",
            Action::DeleteLine => "Delete line",
            Action::InsertLineBelow => "Insert line below",
            Action::InsertLineAbove => "Insert line above",
            Action::Undo => "Undo",
            Action::Redo => "Redo",
            Action::YankLine => "Yank line",
            Action::Paste => "Paste after",
            Action::PasteBefore => "Paste before",
            Action::OperatorDelete => "Delete (operator)",
            Action::OperatorChange => "Change (operator)",
            Action::OperatorYank => "Yank (operator)",
            Action::VisualDelete => "Delete selection",
            Action::VisualChange => "Change selection",
            Action::VisualYank => "Yank selection",
            Action::JumpBack => "Jump back",
            Action::JumpForward => "Jump forward",
            Action::EnterSearchForward => "Search forward",
            Action::EnterSearchBackward => "Search backward",
            Action::SearchNext => "Search next",
            Action::SearchPrev => "Search previous",
            Action::EnterInsertMode => "Enter insert mode",
            Action::EnterInsertModeAppend => "Enter insert mode (append)",
            Action::EnterInsertModeLineEnd => "Enter insert mode (line end)",
            Action::EnterInsertModeLineStart => "Enter insert mode (line start)",
            Action::EnterNormalMode => "Enter normal mode",
            Action::EnterVisualMode => "Enter visual mode",
            Action::EnterCommandMode => "Enter command mode",
            Action::NextBuffer => "Next buffer",
            Action::PrevBuffer => "Previous buffer",
            Action::CloseBuffer => "Close buffer",
            Action::SaveBuffer => "Save buffer",
            Action::SplitVertical => "Split vertical",
            Action::SplitHorizontal => "Split horizontal",
            Action::FocusPaneNext => "Focus next pane",
            Action::FocusPanePrev => "Focus previous pane",
            Action::FocusPaneLeft => "Focus pane left",
            Action::FocusPaneRight => "Focus pane right",
            Action::FocusPaneUp => "Focus pane up",
            Action::FocusPaneDown => "Focus pane down",
            Action::MovePaneLeft => "Move pane left",
            Action::MovePaneRight => "Move pane right",
            Action::MovePaneUp => "Move pane up",
            Action::MovePaneDown => "Move pane down",
            Action::ClosePane => "Close pane",
            Action::OpenFileBrowser => "Open file browser",
            Action::OpenFileBrowserHome => "Open file browser (home)",
            Action::BrowserOpen => "Browser: open",
            Action::BrowserParentDir => "Browser: parent directory",
            Action::BrowserFilter => "Browser: filter",
            Action::BrowserNewFile => "Browser: new file",
            Action::BrowserClose => "Browser: close",
            Action::BrowserHome => "Browser: go home",
            Action::CommandPalette => "Command palette",
            Action::Quit => "Quit (close buffer)",
            Action::ForceQuit => "Force quit (close buffer)",
            Action::QuitAll => "Quit all",
            Action::ForceQuitAll => "Force quit all",
            Action::InsertChar(_) => "Insert char",
            Action::ExecuteCommand(_) => "Execute command",
            Action::SaveBufferAs(_) => "Save buffer as",
            Action::GotoLine(_) => "Go to line",
            Action::SearchExecute(_, _) => "Execute search",
            Action::SearchCancel => "Cancel search",
            Action::Noop => "No-op",
        }
    }

    /// All configurable actions (excludes runtime-only variants).
    pub fn all_configurable() -> Vec<Action> {
        vec![
            Action::MoveUp, Action::MoveDown, Action::MoveLeft, Action::MoveRight,
            Action::MoveWordForward, Action::MoveWordEnd, Action::MoveWordBackward,
            Action::MoveBigWordForward, Action::MoveBigWordEnd, Action::MoveBigWordBackward,
            Action::MoveToLineStart, Action::MoveToLineEnd,
            Action::MoveToFirstLine, Action::MoveToLastLine,
            Action::PageUp, Action::PageDown, Action::HalfPageUp, Action::HalfPageDown,
            Action::ScrollUp, Action::ScrollDown,
            Action::InsertNewline, Action::DeleteCharBackward, Action::DeleteCharForward,
            Action::DeleteLine, Action::InsertLineBelow, Action::InsertLineAbove,
            Action::Undo, Action::Redo,
            Action::YankLine, Action::Paste, Action::PasteBefore,
            Action::OperatorDelete, Action::OperatorChange, Action::OperatorYank,
            Action::JumpBack, Action::JumpForward,
            Action::EnterSearchForward, Action::EnterSearchBackward,
            Action::SearchNext, Action::SearchPrev,
            Action::EnterInsertMode, Action::EnterInsertModeAppend,
            Action::EnterInsertModeLineEnd, Action::EnterInsertModeLineStart,
            Action::EnterNormalMode, Action::EnterVisualMode, Action::EnterCommandMode,
            Action::NextBuffer, Action::PrevBuffer, Action::CloseBuffer, Action::SaveBuffer,
            Action::SplitVertical, Action::SplitHorizontal,
            Action::FocusPaneNext, Action::FocusPanePrev,
            Action::FocusPaneLeft, Action::FocusPaneRight,
            Action::FocusPaneUp, Action::FocusPaneDown,
            Action::MovePaneLeft, Action::MovePaneRight,
            Action::MovePaneUp, Action::MovePaneDown,
            Action::ClosePane,
            Action::OpenFileBrowser, Action::OpenFileBrowserHome,
            Action::BrowserOpen, Action::BrowserParentDir, Action::BrowserFilter,
            Action::BrowserNewFile, Action::BrowserClose, Action::BrowserHome,
            Action::CommandPalette,
            Action::Quit, Action::ForceQuit, Action::QuitAll, Action::ForceQuitAll,
        ]
    }

    /// Whether this action is a motion that can compose with an operator.
    pub fn is_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveUp
                | Action::MoveDown
                | Action::MoveLeft
                | Action::MoveRight
                | Action::MoveWordForward
                | Action::MoveWordEnd
                | Action::MoveWordBackward
                | Action::MoveBigWordForward
                | Action::MoveBigWordEnd
                | Action::MoveBigWordBackward
                | Action::MoveToLineStart
                | Action::MoveToLineEnd
                | Action::MoveToFirstLine
                | Action::MoveToLastLine
                | Action::PageUp
                | Action::PageDown
                | Action::HalfPageUp
                | Action::HalfPageDown
                | Action::GotoLine(_)
        )
    }

    /// Whether this motion is exclusive (destination char NOT included in operator range).
    /// Vim rule: inclusive motions include the destination, exclusive motions don't.
    pub fn is_exclusive_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveLeft
                | Action::MoveRight
                | Action::MoveWordForward
                | Action::MoveWordBackward
                | Action::MoveBigWordForward
                | Action::MoveBigWordBackward
                | Action::MoveToLineStart
        )
    }

    /// Whether this motion operates on whole lines (linewise).
    pub fn is_linewise_motion(&self) -> bool {
        matches!(
            self,
            Action::MoveUp
                | Action::MoveDown
                | Action::MoveToFirstLine
                | Action::MoveToLastLine
                | Action::PageUp
                | Action::PageDown
                | Action::HalfPageUp
                | Action::HalfPageDown
                | Action::GotoLine(_)
        )
    }
}
